---
# tasks file for ansible-role-redis/
- name: Install redis server
  apt:
    name:   redis-server
    state:  latest

- name: Ensure Redis service is started and enabled by default
  service:    
    name:     redis
    state:    started
    enabled:  yes

